name: Automate Pull Requests and Merge for Pullshark Gold

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create_and_merge_prs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      MAX: 1024
      THRESHOLD: 100
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "chrisbanas"
          git config --global user.email "bananas595@gmail.com"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Stress-test prerequisites
        run: |
          echo "GH CLI version: $(gh --version)"
          echo "jq version: $(jq --version)"
          echo "Git version: $(git --version)"

      - name: Generate and merge PRs
        shell: bash
        run: |
          file="merged_prs.txt"
          
          for ((i=1; i<=MAX; i++)); do
            branch="automated-pr-${i}-$(date +%s%N)"
            echo "=== Starting PR #$i on branch $branch ==="

            # Rate limit check
            rem=$(gh api /rate_limit --jq '.resources.core.remaining')
            reset=$(gh api /rate_limit --jq '.resources.core.reset')
            now=$(date +%s)
            if (( rem < THRESHOLD )); then
              wait=$((reset - now + 5))
              echo "Rate limit low: $rem. Sleeping for $wait seconds until reset."
              sleep $wait
            fi

            # Update main
            git checkout main
            git pull --ff-only origin main

            # Create branch
            git checkout -b "$branch"

            # Commit change
            echo "Merged PR #$i at $(date -u)" >> "$file"
            git add "$file"
            git commit -m "chore: update merged PR count #$i" || { echo "No changes to commit"; }

            # Push branch
            git push origin "$branch" --force

            # Create PR with retries
            for attempt in {1..5}; do
              pr_url=$(gh pr create --base main --head "$branch" --title "Automated PR #$i" --body "Automated PR #$i to earn Pullshark Gold badge." 2>/dev/null) && break
              echo "PR creation failed (attempt $attempt). Retrying in $((attempt*5))s..."
              sleep $((attempt*5))
            done
            if [[ -z "$pr_url" ]]; then
              echo "Failed to create PR after retries. Exiting."
              exit 1
            fi
            echo "PR created: $pr_url"

            # Merge PR with retries
            for attempt in {1..5}; do
              gh pr merge "$pr_url" --squash --delete-branch --admin && break
              echo "Merge failed (attempt $attempt). Retrying in $((attempt*5))s..."
              sleep $((attempt*5))
            done
            echo "PR #$i merged successfully"

          done
