name: Automate Pull Requests and Merge for Pullshark Gold

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create_and_merge_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "chrisbanas"
          git config --global user.email "bananas595@gmail.com"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: echo "${GITHUB_TOKEN}" | gh auth login --with-token

      - name: Generate and merge PRs
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        shell: bash
        run: |
          MAX=1024
          THRESHOLD=100
          for i in $(seq 1 $MAX); do
            branch="automated-pr-${i}-$(date +%s)"
            file="merged_prs.txt"
            echo "Starting PR #$i on branch $branch"

            # Rate limit check
            remaining=$(gh api /rate_limit --jq ".resources.core.remaining")
            reset_epoch=$(gh api /rate_limit | jq ".resources.core.reset")
            now=$(date +%s)
            if [ "$remaining" -lt "$THRESHOLD" ]; then
              sleep_time=$((reset_epoch - now + 5))
              echo "Rate limit low: $remaining. Sleeping for $sleep_time seconds..."
              sleep $sleep_time
            fi

            # Update main branch
            git checkout main
            git pull origin main

            # Create new branch
            git checkout -b "$branch"

            # Make a simple change
            echo "Merged PR #$i at $(date -u)" >> "$file"
            git add "$file"
            git commit -m "chore: update merged PR count to #$i"

            # Push and create PR
            git push origin "$branch"
            pr_url=$(gh pr create --base main --head "$branch" --title "Automated PR #$i" --body "Automated PR #$i to earn Pullshark Gold badge.")

            # Merge PR
            gh pr merge "$pr_url" --squash --delete-branch --admin
            echo "Merged PR #$i successfully."
          done
