name: Automate Pull Requests and Merge

on:
  workflow_dispatch:

jobs:
  create_and_merge_prs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set Up Git
        run: |
          git config --global user.name "chrisbanas"
          git config --global user.email "bananas595@gmail.com"

      # Step 3: Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      # Step 4: Authenticate with GitHub CLI
      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      # Step 5: Create and Merge Pull Requests
      - name: Automate PR Creation and Merging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for i in {1..10} # Adjust the range as needed
          do
            branch_name="automated-branch-$i"
            tracker_file="merged_prs.txt"

            # Step 5.1: Create a new branch
            git checkout -b $branch_name

            # Step 5.2: Update a file to simulate changes
            echo "Merged pull request #: $i" >> $tracker_file
            git add $tracker_file
            git commit -m "Update merged PR count to #$i"
            git push origin $branch_name

            # Step 5.3: Create a PR using gh CLI
            pr_url=$(gh pr create --base main --head $branch_name --title "Automated PR #$i" --body "This is an automated pull request created by GitHub Actions.")

            # Step 5.4: Merge the PR
            gh pr merge --squash --delete-branch --admin $pr_url

            # Optional: Sleep to avoid rate limits
            sleep $((RANDOM % 3 + 1))
          done
