name: Automate Pull Requests for Pull Shark Badge

on:
  workflow_dispatch:

jobs:
  create_and_merge_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Git
        run: |
          git config --global user.name "chrisbanas"
          git config --global user.email "bananas595@gmail.com"

      - name: Automate Pull Requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for i in {1..2} # Adjust this range to create the desired number of PRs
          do
            branch_name="automated-branch-$i"
            tracker_file="merged_prs.txt"

            # Create a new branch
            git checkout -b $branch_name

            # Update or initialize the tracker file
            if [ -f "$tracker_file" ]; then
              # Increment the count in the tracker file
              count=$(grep -oE '[0-9]+' $tracker_file)
              count=$((count + 1))
            else
              # Initialize the tracker file
              count=1
            fi

            echo "Merged pull request #: $count" > $tracker_file

            # Add and commit the tracker file
            git add $tracker_file
            git commit -m "Update merged PR count to #$count"

            # Push the branch
            git push origin $branch_name

            # Create a pull request
            pr_url=$(gh pr create --base main --head $branch_name --title "Update merged PR count to #$count" --body "This PR updates the count of merged pull requests to $count.")

            # Merge the pull request
            gh pr merge $pr_url --merge --admin

            # Delete the branch locally and remotely
            git checkout main
            git branch -d $branch_name
            git push origin --delete $branch_name

            # Optional: Sleep to avoid rate limits or conflicts
            sleep $((RANDOM % 3 + 1))
          done
