name: Automate Pull Requests for Pull Shark Badge

on:
  workflow_dispatch:

jobs:
  create_and_merge_prs:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Git configuration
      - name: Set Up Git
        run: |
          git config --global user.name "chrisbanas"
          git config --global user.email "bananas595@gmail.com"

      # Automate Pull Requests
      - name: Automate Pull Requests
        run: |
          for i in {1..2} # Adjust this range to create the desired number of PRs
          do
            branch_name="automated-branch-$i"
            tracker_file="merged_prs.txt"

            # Create a new branch
            git checkout -b $branch_name

            # Update or initialize the tracker file
            if [ -f "$tracker_file" ]; then
              # Increment the count in the tracker file
              count=$(grep -oE '[0-9]+' $tracker_file)
              count=$((count + 1))
            else
              # Initialize the tracker file
              count=1
            fi

            echo "Merged pull request #: $count" > $tracker_file

            # Add and commit the tracker file
            git add $tracker_file
            git commit -m "Update merged PR count to #$count"

            # Push the branch
            git push origin $branch_name

            # Merge the branch into main
            git fetch origin main
            git checkout main
            git merge --no-ff $branch_name -m "Merge branch '$branch_name' into main"

            # Push the updated main branch
            git push origin main

            # Delete the branch locally and remotely
            git branch -d $branch_name
            git push origin --delete $branch_name

            # Optional: Sleep to avoid rate limits or conflicts
            sleep $((RANDOM % 3 + 1))
          done
